Code coverage enhanced

diff --git a/test/check_coverage b/test/check_coverage
--- a/test/check_coverage
+++ b/test/check_coverage
@@ -1,17 +1,31 @@
 #!/bin/sh
 
-set -e
-for f in `find ${srcdir}/../src -name '*.gcda' -print`
+# set -ue: treat unset variables as an error; exit on error
+set -ue
+
+# use absolute paths instead of relative
+top_srcdir=`cd $top_srcdir; pwd`
+top_builddir=`cd $top_builddir; pwd`
+
+for rd in src/lib # relative directories to scan for gcda files
 do
+    for f in `ls -1 ${top_builddir}/${rd}/*.gcda`
+    do
+	test -f $f || continue
+
 	d=`dirname $f`
 	s="`basename $f .gcda`.c"
-	cd $d
-	test -f $s || ln -s ../$s .
-	gcov $s
-	cd -
-done
-echo "Source files with untriggered lines (i.e. .gcov file contains #####):"
-for f in `find ${srcdir}/../src -name '*.gcov'`
-do
+	(cd $d
+	test ! -L $s || rm $s
+	# create links to absolute paths
+	test -f $s || test -L $s || ln -s "`cd ${top_srcdir}/${rd}; pwd`"/$s .
+	gcov $s)
+    done
+    echo "Source files with untriggered lines (i.e. .gcov file contains #####):"
+    for f in `ls -1 ${top_builddir}/${rd}/*.gcov`
+    do
+	test -f $f || continue
+
 	! grep -l '#####' $f
+    done
 done
